services:
  dashboard-react-back:
    container_name: cdashboard-react-back
    restart: unless-stopped
    build: ./back
    volumes:
      - ./data-back:/app/data
    ports:
      - "4009:8000"
    env_file:
      - .env
      - db.env
    depends_on:
      - db

  dashboard-react-front:
    container_name: cdashboard-react-front
    restart: unless-stopped
    build:
      context: ./front
      args:
        VITE_BASE_API_URL: ${VITE_BASE_API_URL}
        VITE_RECAPTCHA_CLIENT_SECRET: ${VITE_RECAPTCHA_CLIENT_SECRET}
    ports:
      - "4010:8080"
    depends_on:
      - dashboard-react-back

  db:
    container_name: cdashboard-react-db
    restart: unless-stopped
    image: postgres:14-alpine
    volumes:
      - ./data-db:/var/lib/postgresql/data
      - ./init/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - ./init/script.sql:/script.sql
    env_file:
      - db.env