services:
  learning-react-back:
    container_name: clearning-react-back
    restart: unless-stopped
    build: ./back
    volumes:
      - ./data-back:/app/data
    ports:
      - "4009:8000"
    env_file:
      - back.env
    depends_on:
      - db

  learning-react-front:
    container_name: clearning-react-front
    restart: unless-stopped
    build:
      context: ./front
      args:
        VITE_BASE_API_URL: http://localhost:4009/api/v1
    env_file:
      - front.env
    ports:
      - "4010:8080"
    depends_on:
      - learning-react-back

  db:
    container_name: clearning-react-db
    restart: unless-stopped
    image: postgres:14-alpine
    volumes:
      - ./data-db:/var/lib/postgresql/data
      - ./init/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - ./init/script.sql:/script.sql
    env_file:
      - db.env