services:
  learning-react-back:
    container_name: clearning-react-back
    restart: unless-stopped
    build: ./back
    volumes:
      - ./data-back:/app/data
    ports:
      - "4009:8000"
    env_file:
      - back.env

  learning-react-build-front:
    container_name: clearning-react-build-front
    restart: unless-stopped
    build:
      context: ./front
      args:
        VITE_BASE_API_URL: http://localhost:4009/api/v1
    ports:
      - "4010:8080"

  db:
    container_name: clearning-react-db
    restart: unless-stopped
    image: postgres:14-alpine
    volumes:
      - ./data-db:/var/lib/postgresql/data
    env_file:
      - db.env