services:
  learning-react-back:
    container_name: clearning-react-back
    restart: unless-stopped
    build: ./back
    volumes:
      - ./data-back:/app/data
    ports:
      - "4009:8000"
    env_file:
      - .docker.env

  learning-react-build-front:
    container_name: clearning-react-build-front
    restart: unless-stopped
    build:
      context: ./front
      args:
        VITE_BASE_API_URL:
    ports:
      - "4010:8080"
